#!/usr/bin/env python3
"""Generate MANIFEST.json from SKILL.md frontmatter.

MANIFEST.json is a build artifact. Edit SKILL.md frontmatter, then run this.

    tools/build-manifest.py            # regenerate MANIFEST.json
    tools/build-manifest.py --check    # exit 1 if it is out of date (CI)

Repo-level fields (version history, removed skills) come from manifest.meta.json,
which is hand-maintained.
"""
import argparse, json, os, re, sys, yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "MANIFEST.json")
META = os.path.join(ROOT, "manifest.meta.json")
PREFIX = "tvv-"
REQUIRED = ["name", "description", "version", "category", "scope", "triggers",
            "status", "created", "last_updated"]
SEMVER = re.compile(r"^\d+\.\d+\.\d+$")


def load_frontmatter(path):
    m = re.match(r"^---\n(.*?)\n---\n", open(path, encoding="utf-8").read(), re.S)
    if not m:
        raise ValueError("missing YAML frontmatter")
    try:
        return yaml.safe_load(m.group(1))
    except yaml.YAMLError as e:
        # Almost always an unquoted description containing a colon.
        raise ValueError(f"frontmatter is not valid YAML: {e}") from None


def collect(errors):
    skills = []
    for d in sorted(os.listdir(ROOT)):
        skill_md = os.path.join(ROOT, d, "SKILL.md")
        if not os.path.isfile(skill_md):
            continue
        try:
            fm = load_frontmatter(skill_md)
        except ValueError as e:
            errors.append(f"{d}/SKILL.md: {e}")
            continue
        for key in REQUIRED:
            if not fm.get(key):
                errors.append(f"{d}/SKILL.md: missing required frontmatter '{key}'")
        if not d.startswith(PREFIX):
            errors.append(f"{d}/: directory name must start with '{PREFIX}'")
        if fm.get("name") != d:
            errors.append(f"{d}/SKILL.md: name '{fm.get('name')}' must match directory '{d}'")
        version = str(fm.get("version", ""))
        if version and not SEMVER.match(version):
            errors.append(f"{d}/SKILL.md: version '{version}' is not MAJOR.MINOR.PATCH")
        skills.append({
            "name": fm.get("name"),
            "version": version,
            "category": fm.get("category"),
            "scope": fm.get("scope"),
            "description": fm.get("description"),
            "path": f"{d}/",
            "triggers": fm.get("triggers"),
            "created": str(fm.get("created", "")),
            "last_updated": str(fm.get("last_updated", "")),
            "status": fm.get("status"),
        })
    return skills


def build():
    errors = []
    skills = collect(errors)
    if errors:
        print("build-manifest: frontmatter problems\n  " + "\n  ".join(errors), file=sys.stderr)
        sys.exit(1)
    meta = json.load(open(META, encoding="utf-8"))
    return {
        "_generated": "Generated by tools/build-manifest.py from SKILL.md frontmatter. Do not edit by hand.",
        "repository": meta["repository"],
        "description": meta["description"],
        "version": meta["version"],
        "last_updated": meta["last_updated"],
        "skills": skills,
        "versions": meta["versions"],
        "removed": meta["removed"],
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="verify MANIFEST.json matches frontmatter; do not write")
    args = ap.parse_args()

    manifest = build()
    text = json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"

    if args.check:
        current = open(MANIFEST, encoding="utf-8").read() if os.path.exists(MANIFEST) else ""
        if current != text:
            print("MANIFEST.json is out of date. Run: tools/build-manifest.py", file=sys.stderr)
            sys.exit(1)
        print(f"MANIFEST.json is up to date ({len(manifest['skills'])} skills)")
        return

    open(MANIFEST, "w", encoding="utf-8").write(text)
    print(f"wrote MANIFEST.json ({len(manifest['skills'])} skills)")


if __name__ == "__main__":
    main()
